Updated Dockerfile
CodeChefVIT/deployments pull request #7
Opened 2019-08-01 18:25 UTC by RishabhKodes

2019-08-01 21:36 UTC, L04DB4L4NC3R requested changes

2019-08-01 21:36 UTC, L04DB4L4NC3R commented on Dockerfile
> +COPY    package.json /app
No need to specify `/app` since your workdir context is already inside that dir,.You can use `.` (current dir context) here.

2019-08-01 21:36 UTC, L04DB4L4NC3R commented on Dockerfile
>  EXPOSE   81
Make sure your application is running on the same port that you are exposing

2019-08-01 21:36 UTC, L04DB4L4NC3R commented on Dockerfile
> +CMD node app.js
No need for this. `CMD  ["npm","start"]` is going to suffice provided that there is a start script in package.json. If there is not then do add it

2019-08-01 21:36 UTC, L04DB4L4NC3R commented on Dockerfile
> +CMD node app.js
Don;t put both of these. Use either one

2019-08-02 05:14 UTC, RishabhKodes reviewed
Changes Approved

2019-08-02 09:23 UTC, L04DB4L4NC3R commented
@RishabhKodes This is a bit incorrect. Merging for now, will rectify it myself. @DiptoChakrabarty  Make sure to take a pull from master when working further

2019-08-02 09:23 UTC, merged